### ISSUE TITLE
api na pridanie/aktivovanie aktivity

### ISSUE THREAD

**Issue by xmasny** [spirka3/wtam#6]
send:

{
user_id: 10
activity_id: 8
}

**Comment by Fancman** [comment]
Add into progress all tasks from activity [POST] https://www.polkadot-hub.eu/api/add-activity

{
	"user_id" : 10,
	"activity_id": 6
}



Return if succesful:

{
  "message": "Inserted 8 rows."
}

Error Response Codes: 400 - Wrong request/Database error
