### ISSUE TITLE
vytvorit api na update stavu jednej a viacerych uloh

### ISSUE THREAD

**Issue by xmasny** [spirka3/wtam#7]

**Comment by Fancman** [comment]
Create task progress or update stav [POST] https://www.polkadot-hub.eu/api/activities
Task state musi byt: splnene, nesplnene, rozpracovane. Bez pola task state sa vytvori novy task v tabulke new_task_progress

{
	"user_id" : 10,
	"task_id": 1,
	"task_state": "nesplnene"
}


Return if succesful:

{
  "activity_id": "1",
  "task_id": 1,
  "affected_rows": 1
}

Error Response Codes: 400 - Wrong request/Database error
