### ISSUE TITLE
api na zobrazenie aktivit/odboriek ktore su kompletne splnene

### ISSUE THREAD

**Issue by xmasny** [spirka3/wtam#8]
send: user_id
return: array(of completed) activities

**Comment by Fancman** [comment]
Get completed aktivity pre usera s ulohami [POST] https://www.polkadot-hub.eu/api/completed

{
	"user_id" : 10
}


Return if succesful:

  {
    "id": "1",
    "name": "Táborník",
    "img_url": "https:\/\/www.skauting.sk\/wp-content\/uploads\/2017\/04\/skauting-program-odborka-skauti-z-25-200x200.png",
    "level": "Zelený",
    "activity_type": "Odborky",
    "age_category_id": "2",
    "age_category": "Skauti a skautky",
    "ulohy": [
      {
        "id": "1",
        "description": "Prespal som aspoň 20 nocí pod stanom (pod širákom či prístreškom).",
        "activity_id": "1"
      },
      {
        "id": "2",
        "description": "Zúčastnil som sa stavania aspoň jednej väčšej táborovej stavby (brána, kuchyňa, típí, podsada…).",
        "activity_id": "1"
      },
      {
        "id": "3",
        "description": "S použitím sekery, KPZ a jedného polena som priviedol do varu liter vody.",
        "activity_id": "1"
      }...
	]
  }
}

Error Response Codes: 400 - Wrong request/Database error
